[Addon]
Name[zh_CN]=AI Later
Name=AI Later
Comment[zh_CN]=AI来输入法
Comment=AI-powered input method
Category=InputMethod
Version=0.1.0
Library=libailater_im
Type=SharedLibrary
OnDemand=True
Configurable=True

[Addon/Dependencies]
0=core