[Addon]
Name=ai-later
Category=InputMethod
Version=0.1.0
Library=libailater_im
Type=SharedLibrary
OnDemand=True
Configurable=True

[Addon/Dependencies]
0=core

[InputMethod]
Name=AI Later
Icon=ailater-im
Label=AI
LanguageCode=zh_CN
Priority=100
